import { isAfter, isBefore, isEqual, parseISO } from 'date-fns'
import { nanoid } from 'nanoid'
import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { CalendarEvent } from '../types'
import { buildAutoEvents } from '../utils/syncCalendar'
import { useApplicationStore } from './useApplicationStore'
import { useCompanyStore } from './useCompanyStore'
import { useInterviewStore } from './useInterviewStore'

interface CalendarState {
  events: CalendarEvent[]
  showAutoGenerated: boolean
  addEvent: (payload: Omit<CalendarEvent, 'id' | 'isAutoGenerated'>) => string
  updateEvent: (id: string, payload: Partial<CalendarEvent>) => void
  deleteEvent: (id: string) => void
  setShowAutoGenerated: (value: boolean) => void
  syncFromOtherStores: () => void
  getById: (id: string) => CalendarEvent | undefined
  getEventsByDate: (date: string) => CalendarEvent[]
  getEventsInRange: (start: string, end: string) => CalendarEvent[]
  getTodayEvents: () => CalendarEvent[]
  getUpcomingEvents: (days: number) => CalendarEvent[]
}

export const useCalendarStore = create<CalendarState>()(
  persist(
    (set, get) => ({
      events: [],
      showAutoGenerated: true,
      addEvent: (payload) => {
        const id = nanoid()
        set((state) => ({ events: [{ id, isAutoGenerated: false, ...payload }, ...state.events] }))
        return id
      },
      updateEvent: (id, payload) =>
        set((state) => ({
          events: state.events.map((item) => {
            if (item.id !== id || item.isAutoGenerated) return item
            return { ...item, ...payload }
          }),
        })),
      deleteEvent: (id) => set((state) => ({ events: state.events.filter((item) => item.id !== id) })),
      setShowAutoGenerated: (value) => set({ showAutoGenerated: value }),
      syncFromOtherStores: () => {
        const companies = useCompanyStore.getState().companies
        const applications = useApplicationStore.getState().applications
        const interviews = useInterviewStore.getState().interviews
        const auto = buildAutoEvents(companies, applications, interviews)
        set((state) => ({ events: [...state.events.filter((item) => !item.isAutoGenerated), ...auto] }))
      },
      getById: (id) => get().events.find((item) => item.id === id),
      getEventsByDate: (date) =>
        get().events.filter((item) => item.date === date && (get().showAutoGenerated || !item.isAutoGenerated)),
      getEventsInRange: (start, end) =>
        get().events.filter((item) => {
          if (!get().showAutoGenerated && item.isAutoGenerated) return false
          const d = parseISO(item.date)
          return (isAfter(d, parseISO(start)) || isEqual(d, parseISO(start))) && (isBefore(d, parseISO(end)) || isEqual(d, parseISO(end)))
        }),
      getTodayEvents: () => {
        const today = new Date().toISOString().slice(0, 10)
        return get().getEventsByDate(today)
      },
      getUpcomingEvents: (days) => {
        const start = new Date().toISOString().slice(0, 10)
        const end = new Date(Date.now() + days * 86400000).toISOString().slice(0, 10)
        return get().getEventsInRange(start, end)
      },
    }),
    {
      name: 'autumnhunt-calendar',
      version: 1,
      partialize: (state) => ({ events: state.events, showAutoGenerated: state.showAutoGenerated }),
    },
  ),
)
