import { Building2, Calendar, Globe, LayoutDashboard, MessageSquare, Send, Settings, Sparkles } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { useCalendarStore } from '../../store/useCalendarStore'
import { cn } from '../../lib/utils'

const navItems = [
  { to: '/', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/calendar', label: '日历', icon: Calendar },
  { to: '/companies', label: '公司库', icon: Building2 },
  { to: '/applications', label: '投递追踪', icon: Send },
  { to: '/interviews', label: '面试记录', icon: MessageSquare },
  { to: '/settings', label: '设置', icon: Settings },
]

export default function Sidebar() {
  const events = useCalendarStore((s) => s.events)
  const showAutoGenerated = useCalendarStore((s) => s.showAutoGenerated)
  const today = new Date().toISOString().slice(0, 10)
  const todoCount = events.filter((e) => e.date === today && (showAutoGenerated || !e.isAutoGenerated)).length

  return (
    <aside className="fixed left-0 top-0 flex h-screen w-60 flex-col border-r border-neutral-border bg-[linear-gradient(rgba(232,213,183,0.3),rgba(232,213,183,0.3)),#FAF7F2] p-4">
      <div className="mb-8 px-2 py-4">
        <h1 className="font-serif text-3xl tracking-tight text-neutral-text">
          AutumnHunt <span className="text-[1.3em] leading-none">🌾</span>
        </h1>
      </div>

      <nav className="flex-1 space-y-1">
        {navItems.map((item) => {
          const Icon = item.icon
          return (
            <NavLink
              key={item.to}
              to={item.to}
              end={item.to === '/'}
              className={({ isActive }) =>
                cn(
                  'relative flex items-center justify-between rounded-2xl px-4 py-3 text-sm text-neutral-muted transition-colors hover:bg-primary-cream/25 hover:text-neutral-text',
                  isActive && 'bg-primary-cream/35 text-neutral-text',
                )
              }
            >
              {({ isActive }) => (
                <>
                  {isActive && <span className="absolute left-0 top-2 h-8 w-1 rounded-r bg-primary-cream" />}
                  <span className="inline-flex items-center gap-3">
                    <Icon className="h-4 w-4" />
                    <span>{item.label}</span>
                  </span>
                  {item.to === '/calendar' && todoCount > 0 && (
                    <span className="rounded-full bg-primary-rose px-1.5 py-0.5 text-[11px] text-white">{todoCount > 9 ? '9+' : todoCount}</span>
                  )}
                </>
              )}
            </NavLink>
          )
        })}
      </nav>

      <div className="space-y-2 border-t border-neutral-border px-2 pt-4 text-sm text-neutral-muted">
        <p>v0.3.0</p>
        <a href="https://你的用户名.github.io/autumnhunt" className="inline-flex items-center gap-2 hover:text-neutral-text" target="_blank" rel="noreferrer">
          <Sparkles className="h-4 w-4" /> ✨ 在线体验
        </a>
        <a href="https://github.com/ZHANG-Shuyue/autumnhunt" className="inline-flex items-center gap-2 hover:text-neutral-text" target="_blank" rel="noreferrer">
          <Globe className="h-4 w-4" /> GitHub
        </a>
      </div>
    </aside>
  )
}
