import { Link2, Sparkles } from 'lucide-react'
import type { CalendarEvent } from '../../types'
import EventTypeBadge from './EventTypeBadge'

const colorMap: Record<string, string> = {
  cream: 'bg-primary-cream',
  mist: 'bg-primary-mist',
  rose: 'bg-primary-rose',
  sage: 'bg-primary-sage',
  ash: 'bg-primary-ash',
}

export default function EventCard({ event }: { event: CalendarEvent }) {
  return (
    <div className="rounded-xl border border-neutral-border bg-white p-3">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className={`h-2.5 w-2.5 rounded-full ${colorMap[event.color ?? 'cream']}`} />
          <p className="text-sm font-medium text-neutral-text">{event.title}</p>
        </div>
        <EventTypeBadge type={event.type} />
      </div>
      <div className="mt-2 flex items-center gap-2 text-xs text-neutral-muted">
        {event.time ? <span>{event.time}{event.endTime ? ` - ${event.endTime}` : ''}</span> : <span>全天</span>}
        {event.isAutoGenerated && <span className="inline-flex items-center gap-1"><Sparkles className="h-3 w-3" />系统同步</span>}
        {event.linkedTo && <span className="inline-flex items-center gap-1"><Link2 className="h-3 w-3" />已关联</span>}
      </div>
      {event.description && <p className="mt-2 text-xs text-neutral-muted">{event.description}</p>}
    </div>
  )
}
