export interface CompanyLink {
  title: string
  url: string
}

export interface CompanyAttachment {
  name: string
  url: string
}

export interface Company {
  id: string
  name: string
  logo?: string
  industry: string
  status: 'open' | 'closed' | 'upcoming'
  applyUrl: string
  positions: string[]
  deadline?: string
  description?: string
  source: string
  createdAt: string
  updatedAt: string
  contactInfo?: string
  referralCode?: string
  baseLocation?: string
  salaryRange?: string
  researchNotes?: string
  relatedLinks?: CompanyLink[]
  attachments?: CompanyAttachment[]
}

export interface Application {
  id: string
  companyId: string
  position: string
  resumeFile?: string
  status: 'applied' | 'written_test' | 'interviewing' | 'offer' | 'rejected'
  appliedAt: string
  notes?: string
  writtenTestAt?: string
  writtenTestResult?: 'pending' | 'passed' | 'failed'
  finalResult?: 'pending' | 'offer' | 'rejected' | 'withdrawn'
  preparationDocUrl?: string
  updatedAt: string
}

export interface Interview {
  id: string
  applicationId: string
  round: string
  scheduledAt: string
  interviewer?: string
  questions?: string
  selfReview?: string
  rating?: number
  duration?: number
  format?: 'onsite' | 'video' | 'phone'
  location?: string
  updatedAt: string
}

export interface CalendarEvent {
  id: string
  title: string
  date: string
  time?: string
  endTime?: string
  type: string
  color?: 'cream' | 'mist' | 'rose' | 'sage' | 'ash'
  description?: string
  linkedTo?: {
    kind: 'company' | 'application' | 'interview'
    id: string
  }
  isAutoGenerated: boolean
  updatedAt: string
}
