export interface CompanyLink {
  title: string
  url: string
}

export interface CompanyAttachment {
  name: string
  url: string
}

export type ResumeSource = 'pdf' | 'link'

export interface Resume {
  id: string
  name: string
  category: string
  version: number
  isActive: boolean
  source: ResumeSource
  fileName?: string
  filePath?: string
  fileSize?: number
  externalUrl?: string
  notes?: string
  createdAt: string
  updatedAt: string
}

export interface RecruitingLink {
  id: string
  label: string
  url: string
  type: 'official' | 'jd' | 'referral' | 'note' | 'other'
  note?: string
  createdAt: string
}

export interface Company {
  id: string
  name: string
  logo?: string
  industry: string
  status: 'open' | 'closed' | 'upcoming'
  applyUrl: string
  positions: string[]
  deadline?: string
  description?: string
  source: string
  createdAt: string
  updatedAt: string
  contactInfo?: string
  referralCode?: string
  baseLocation?: string
  salaryRange?: string
  researchNotes?: string
  relatedLinks?: CompanyLink[]
  attachments?: CompanyAttachment[]
  recruitingLinks?: RecruitingLink[]
}

export interface Application {
  id: string
  companyId: string
  position: string
  resumeId?: string
  status: 'applied' | 'written_test' | 'interviewing' | 'offer' | 'rejected'
  appliedAt: string
  notes?: string
  writtenTestAt?: string
  writtenTestResult?: 'pending' | 'passed' | 'failed'
  finalResult?: 'pending' | 'offer' | 'rejected' | 'withdrawn'
  preparationDocUrl?: string
  jobUrl?: string
  updatedAt: string
}

export interface Interview {
  id: string
  applicationId: string
  round: string
  scheduledAt: string
  interviewer?: string
  questions?: string
  selfReview?: string
  rating?: number
  duration?: number
  format?: 'onsite' | 'video' | 'phone'
  location?: string
  result?: 'pending' | 'pass' | 'fail'
  updatedAt: string
}

export interface CalendarEvent {
  id: string
  title: string
  date: string
  time?: string
  endTime?: string
  type: string
  color?: 'cream' | 'mist' | 'rose' | 'sage' | 'ash'
  description?: string
  linkedTo?: {
    kind: 'company' | 'application' | 'interview'
    id: string
  }
  isAutoGenerated: boolean
  updatedAt: string
}

export interface CloudPayload {
  version: 1
  updatedAt: string
  device: string
  companies: Company[]
  applications: Application[]
  interviews: Interview[]
  resumes: Resume[]
  mailAccounts?: MailAccount[]
}

// ===== Mail Accounts =====
export type MailProvider = 'gmail' | 'outlook'
export type MailAccountStatus = 'connected' | 'expired' | 'error' | 'syncing'

export interface MailAccount {
  id: string
  provider: MailProvider
  email: string
  displayName?: string
  connectedAt: string
  lastSyncAt?: string
  lastSyncCount?: number
  status: MailAccountStatus
  errorMessage?: string
}

// ===== LLM Config（BYO Key，统一 OpenAI 兼容协议） =====
export interface LLMConfig {
  baseUrl: string
  apiKey: string
  model: string
  presetId?: string
  savedAt: string
  lastTestAt?: string
  lastTestOk?: boolean
  lastTestError?: string
}
