import { endOfMonth, format, startOfMonth } from 'date-fns'
import { ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react'
import { useMemo, useState } from 'react'
import { toast } from 'sonner'
import EventDialog from '../components/calendar/EventDialog'
import EventCard from '../components/calendar/EventCard'
import MonthView from '../components/calendar/MonthView'
import TimelineView from '../components/calendar/TimelineView'
import ConfirmDialog from '../components/common/ConfirmDialog'
import EmptyState from '../components/common/EmptyState'
import { Button } from '../components/ui/button'
import { Card } from '../components/ui/card'
import { Popover, PopoverContent, PopoverTrigger } from '../components/ui/popover'
import { Tabs, TabsList, TabsTrigger } from '../components/ui/tabs'
import type { CalendarEvent } from '../types'
import { shiftMonth, toISODate } from '../utils/date'
import { useCalendarStore } from '../store/useCalendarStore'

export default function CalendarPage() {
  const {
    events,
    addEvent,
    updateEvent,
    deleteEvent,
    syncFromOtherStores,
    showAutoGenerated,
    setShowAutoGenerated,
  } = useCalendarStore()

  const [cursor, setCursor] = useState(new Date())
  const [view, setView] = useState<'month' | 'timeline'>('month')
  const [dialogOpen, setDialogOpen] = useState(false)
  const [activeDate, setActiveDate] = useState(toISODate(new Date()))
  const [editing, setEditing] = useState<CalendarEvent | undefined>()
  const [preview, setPreview] = useState<CalendarEvent | undefined>()
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const [types, setTypes] = useState<string[]>([])

  const allTypes = Array.from(new Set(events.map((e) => e.type)))

  const monthEvents = useMemo(() => {
    const start = toISODate(startOfMonth(cursor))
    const end = toISODate(endOfMonth(cursor))
    const base = events.filter((e) => e.date >= start && e.date <= end)
    const visible = showAutoGenerated ? base : base.filter((e) => !e.isAutoGenerated)
    return types.length ? visible.filter((e) => types.includes(e.type)) : visible
  }, [cursor, events, showAutoGenerated, types])

  return (
    <div className="space-y-5">
      <Card className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="inline-flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => setCursor((prev) => shiftMonth(prev, -1))}><ChevronLeft className="h-4 w-4" /></Button>
            <Button variant="outline" size="sm" onClick={() => setCursor(new Date())}>今天</Button>
            <Button variant="outline" size="sm" onClick={() => setCursor((prev) => shiftMonth(prev, 1))}><ChevronRight className="h-4 w-4" /></Button>
            <span className="ml-2 text-lg font-semibold">{format(cursor, 'yyyy年MM月')}</span>
          </div>

          <Tabs value={view} onValueChange={(v) => setView(v as typeof view)}>
            <TabsList>
              <TabsTrigger value="month">月视图</TabsTrigger>
              <TabsTrigger value="timeline">时间线视图</TabsTrigger>
            </TabsList>
          </Tabs>

          <div className="flex items-center gap-2">
            <Button onClick={() => { setEditing(undefined); setDialogOpen(true) }}>+ 新建事件</Button>
            <Button variant="outline" size="icon" onClick={() => { syncFromOtherStores(); toast.success('同步完成') }}><RefreshCw className="h-4 w-4" /></Button>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button size="sm" variant={showAutoGenerated ? 'default' : 'outline'} onClick={() => setShowAutoGenerated(!showAutoGenerated)}>
            {showAutoGenerated ? '隐藏系统同步事件' : '显示系统同步事件'}
          </Button>
          {allTypes.map((type) => {
            const active = types.includes(type)
            return (
              <button
                key={type}
                type="button"
                onClick={() => setTypes((prev) => (active ? prev.filter((t) => t !== type) : [...prev, type]))}
                className={`rounded-full border px-3 py-1 text-xs ${active ? 'border-primary-cream bg-primary-cream/40' : 'border-neutral-border bg-white'}`}
              >
                {type}
              </button>
            )
          })}
        </div>
      </Card>

      {view === 'month' ? (
        <MonthView
          cursor={cursor}
          events={monthEvents}
          onSelectDate={(date) => {
            setActiveDate(date)
            setEditing(undefined)
            setDialogOpen(true)
          }}
          onSelectEvent={(event) => setPreview(event)}
        />
      ) : monthEvents.length ? (
        <TimelineView events={monthEvents} days={30} />
      ) : (
        <EmptyState text="未来 30 天还没有日程，去添加一个吧 ✨" />
      )}

      <EventDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        initial={editing ? editing : ({ date: activeDate } as CalendarEvent)}
        onSave={(values) => {
          const payload = {
            title: values.title,
            type: values.type,
            color: values.color,
            date: values.date,
            time: values.time || undefined,
            endTime: values.endTime || undefined,
            description: values.description || undefined,
            linkedTo: values.linkedKind && values.linkedId ? { kind: values.linkedKind, id: values.linkedId } : undefined,
          }
          if (editing) updateEvent(editing.id, payload)
          else addEvent(payload)
          setCursor(new Date(values.date))
        }}
      />

      <Popover open={!!preview} onOpenChange={(o) => !o && setPreview(undefined)}>
        <PopoverTrigger asChild><span /></PopoverTrigger>
        <PopoverContent>
          {preview && (
            <div className="space-y-3">
              <EventCard event={preview} />
              <div className="flex justify-end gap-2">
                {!preview.isAutoGenerated && (
                  <>
                    <Button size="sm" variant="outline" onClick={() => { setEditing(preview); setDialogOpen(true); setPreview(undefined) }}>编辑</Button>
                    <Button size="sm" variant="destructive" onClick={() => { setDeletingId(preview.id); setPreview(undefined) }}>删除</Button>
                  </>
                )}
              </div>
            </div>
          )}
        </PopoverContent>
      </Popover>

      <ConfirmDialog
        open={!!deletingId}
        onOpenChange={(open) => !open && setDeletingId(null)}
        title="删除事件"
        description="删除后将无法恢复。"
        onConfirm={() => {
          if (!deletingId) return
          deleteEvent(deletingId)
          toast.success('已删除')
          setDeletingId(null)
        }}
      />
    </div>
  )
}
