import { endOfMonth, format, startOfMonth } from 'date-fns'
import { ArrowRight, ChevronLeft, ChevronRight, Link2, RefreshCw, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import EventDialog from '../components/calendar/EventDialog'
import EventTypeBadge from '../components/calendar/EventTypeBadge'
import MonthView from '../components/calendar/MonthView'
import ConfirmDialog from '../components/common/ConfirmDialog'
import EmptyState from '../components/common/EmptyState'
import { Button } from '../components/ui/button'
import { Card } from '../components/ui/card'
import { Popover, PopoverContent, PopoverTrigger } from '../components/ui/popover'
import { Tabs, TabsList, TabsTrigger } from '../components/ui/tabs'
import type { CalendarEvent } from '../types'
import { shiftMonth, toISODate } from '../utils/date'
import { useCalendarStore } from '../store/useCalendarStore'
import { pushActivity } from '../utils/activity'

export default function CalendarPage() {
  const navigate = useNavigate()
  const { events, addEvent, updateEvent, deleteEvent, syncFromOtherStores, showAutoGenerated, setShowAutoGenerated } = useCalendarStore()

  const [cursor, setCursor] = useState(new Date())
  const [view, setView] = useState<'month' | 'timeline'>('month')
  const [dialogOpen, setDialogOpen] = useState(false)
  const [activeDate, setActiveDate] = useState(toISODate(new Date()))
  const [editing, setEditing] = useState<CalendarEvent | undefined>()
  const [preview, setPreview] = useState<CalendarEvent | undefined>()
  const [deletingId, setDeletingId] = useState<string | null>(null)
  const [types, setTypes] = useState<string[]>([])

  const allTypes = Array.from(new Set(events.map((e) => e.type)))

  const monthEvents = useMemo(() => {
    const start = toISODate(startOfMonth(cursor))
    const end = toISODate(endOfMonth(cursor))
    const base = events.filter((e) => e.date >= start && e.date <= end)
    const visible = showAutoGenerated ? base : base.filter((e) => !e.isAutoGenerated)
    return types.length ? visible.filter((e) => types.includes(e.type)) : visible
  }, [cursor, events, showAutoGenerated, types])

  const timelineSections = useMemo(() => {
    const grouped = new Map<string, CalendarEvent[]>()
    monthEvents.forEach((event) => {
      const key = event.date
      if (!grouped.has(key)) grouped.set(key, [])
      grouped.get(key)?.push(event)
    })

    return [...grouped.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([date, list]) => ({
        date,
        list: list.slice().sort((a, b) => (a.time ?? '99:99').localeCompare(b.time ?? '99:99')),
      }))
  }, [monthEvents])

  const jumpToSource = (event: CalendarEvent) => {
    if (!event.linkedTo) return
    if (event.linkedTo.kind === 'application') navigate(`/applications/${event.linkedTo.id}`)
    if (event.linkedTo.kind === 'interview') navigate('/interviews')
    if (event.linkedTo.kind === 'company') navigate(`/companies/${event.linkedTo.id}`)
  }

  return (
    <div className="space-y-5">
      <Card className="space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="inline-flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => setCursor((prev) => shiftMonth(prev, -1))}><ChevronLeft className="h-4 w-4" /></Button>
            <Button variant="outline" size="sm" onClick={() => setCursor(new Date())}>今天</Button>
            <Button variant="outline" size="sm" onClick={() => setCursor((prev) => shiftMonth(prev, 1))}><ChevronRight className="h-4 w-4" /></Button>
            <span className="ml-2 text-lg font-semibold">{format(cursor, 'yyyy年MM月')}</span>
          </div>

          <Tabs value={view} onValueChange={(v) => setView(v as typeof view)}>
            <TabsList>
              <TabsTrigger value="month">月视图</TabsTrigger>
              <TabsTrigger value="timeline">时间线视图</TabsTrigger>
            </TabsList>
          </Tabs>

          <div className="flex items-center gap-2">
            <Button onClick={() => { setEditing(undefined); setDialogOpen(true) }}>+ 新建事件</Button>
            <Button variant="outline" size="icon" onClick={() => { syncFromOtherStores(); pushActivity('手动同步日历事件'); toast.success('同步完成') }}><RefreshCw className="h-4 w-4" /></Button>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button size="sm" variant={showAutoGenerated ? 'default' : 'outline'} onClick={() => setShowAutoGenerated(!showAutoGenerated)}>
            {showAutoGenerated ? '隐藏系统同步事件' : '显示系统同步事件'}
          </Button>
          {allTypes.map((type) => {
            const active = types.includes(type)
            return (
              <button
                key={type}
                type="button"
                onClick={() => setTypes((prev) => (active ? prev.filter((t) => t !== type) : [...prev, type]))}
                className={`rounded-full border px-3 py-1 text-xs ${active ? 'border-primary-cream bg-primary-cream/40' : 'border-neutral-border bg-white'}`}
              >
                {type}
              </button>
            )
          })}
        </div>
      </Card>

      {view === 'month' ? (
        <MonthView
          cursor={cursor}
          events={monthEvents}
          onSelectDate={(date) => {
            setActiveDate(date)
            setEditing(undefined)
            setDialogOpen(true)
          }}
          onSelectEvent={(event) => setPreview(event)}
        />
      ) : timelineSections.length ? (
        <Card className="max-h-[68vh] overflow-y-auto">
          <div className="space-y-4">
            {timelineSections.map((section) => (
              <section key={section.date} className="rounded-xl border border-neutral-border bg-white p-3">
                <h3 className="mb-2 text-sm font-semibold text-neutral-text">
                  {format(new Date(`${section.date}T00:00:00`), 'yyyy-MM-dd EEEE')}
                </h3>
                <div className="space-y-2">
                  {section.list.map((event) => (
                    <button key={event.id} type="button" className="block w-full text-left" onClick={() => setPreview(event)}>
                      <div className="rounded-lg border border-neutral-border bg-neutral-bg px-3 py-2 text-sm">
                        <p className="font-medium text-neutral-text">{event.title}</p>
                        <p className="mt-1 text-xs text-neutral-muted">{event.time ? `${event.time}${event.endTime ? ` - ${event.endTime}` : ''}` : '全天'} · {event.type}</p>
                      </div>
                    </button>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </Card>
      ) : (
        <EmptyState text="本月暂无事件" />
      )}

      <EventDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        initial={editing ? editing : ({ date: activeDate } as CalendarEvent)}
        onSave={(values) => {
          const payload = {
            title: values.title,
            type: values.type,
            color: values.color,
            date: values.date,
            time: values.time || undefined,
            endTime: values.endTime || undefined,
            description: values.description || undefined,
            linkedTo: values.linkedKind && values.linkedId ? { kind: values.linkedKind, id: values.linkedId } : undefined,
          }
          if (editing) { updateEvent(editing.id, payload); pushActivity(`更新日历事件：${payload.title}`) }
          else { addEvent(payload); pushActivity(`新增日历事件：${payload.title}`) }
          setCursor(new Date(values.date))
        }}
      />

      {/* v0.2.1: 事件 Popover 信息增强 + 跳转源记录 */}
      <Popover open={!!preview} onOpenChange={(o) => !o && setPreview(undefined)}>
        <PopoverTrigger asChild><span /></PopoverTrigger>
        <PopoverContent className="w-80 rounded-xl border border-neutral-border bg-neutral-card p-3 shadow-soft">
          {preview && (
            <div className="space-y-3">
              <div>
                <h4 className="text-base font-semibold">{preview.title}</h4>
                <div className="mt-1 flex items-center gap-2"><EventTypeBadge type={preview.type} />{preview.isAutoGenerated && <span className="inline-flex items-center gap-1 text-xs text-neutral-muted"><Sparkles className="h-3 w-3" />系统同步</span>}</div>
                <p className="mt-2 text-sm text-neutral-muted">时间：{preview.date} {preview.time ? `${preview.time}${preview.endTime ? ` - ${preview.endTime}` : ''}` : '全天'}</p>
                {preview.description && <p className="mt-1 text-sm text-neutral-muted">描述：{preview.description}</p>}
                {preview.linkedTo && <p className="mt-1 inline-flex items-center gap-1 text-sm text-neutral-muted"><Link2 className="h-3 w-3" />关联：{preview.linkedTo.kind} / {preview.linkedTo.id}</p>}
              </div>
              {preview.isAutoGenerated ? (
                <div className="space-y-2">
                  <p className="text-xs text-neutral-muted">由 {preview.type} 自动同步</p>
                  <Button size="sm" variant="outline" onClick={() => jumpToSource(preview)}>前往源记录 <ArrowRight className="ml-1 h-3 w-3" /></Button>
                </div>
              ) : (
                <div className="flex justify-end gap-2">
                  <Button size="sm" variant="outline" onClick={() => { setEditing(preview); setDialogOpen(true); setPreview(undefined) }}>编辑</Button>
                  <Button size="sm" variant="destructive" onClick={() => { setDeletingId(preview.id); setPreview(undefined) }}>删除</Button>
                </div>
              )}
            </div>
          )}
        </PopoverContent>
      </Popover>

      <ConfirmDialog
        open={!!deletingId}
        onOpenChange={(open) => !open && setDeletingId(null)}
        title="删除事件"
        description="删除后将无法恢复。"
        onConfirm={() => {
          if (!deletingId) return
          const title = events.find((e) => e.id === deletingId)?.title ?? '事件'
          deleteEvent(deletingId)
          pushActivity(`删除日历事件：${title}`)
          toast.success('已删除')
          setDeletingId(null)
        }}
      />
    </div>
  )
}
