import { format } from 'date-fns'
import type { Application, CalendarEvent, Company, Interview } from '../types'

const keyOf = (linkedTo: CalendarEvent['linkedTo'], type: string, date: string) => `${linkedTo?.kind}-${linkedTo?.id}-${type}-${date}`

export function buildAutoEvents(companies: Company[], applications: Application[], interviews: Interview[]): CalendarEvent[] {
  const byId = new Map(companies.map((c) => [c.id, c]))
  const events: CalendarEvent[] = []

  companies.forEach((company) => {
    if (!company.deadline) return
    events.push({
      id: `auto-company-deadline-${company.id}`,
      title: `${company.name} 截止`,
      date: company.deadline,
      type: '截止',
      color: 'ash',
      linkedTo: { kind: 'company', id: company.id },
      isAutoGenerated: true,
    })
  })

  applications.forEach((app) => {
    const company = byId.get(app.companyId)
    events.push({
      id: `auto-application-applied-${app.id}`,
      title: `${company?.name ?? '未知公司'} 投递`,
      date: app.appliedAt,
      type: '投递',
      color: 'mist',
      linkedTo: { kind: 'application', id: app.id },
      isAutoGenerated: true,
    })
    if (app.writtenTestAt) {
      events.push({
        id: `auto-application-test-${app.id}`,
        title: `${company?.name ?? '未知公司'} 笔试`,
        date: app.writtenTestAt,
        type: '笔试',
        color: 'cream',
        linkedTo: { kind: 'application', id: app.id },
        isAutoGenerated: true,
      })
    }
  })

  interviews.forEach((interview) => {
    const app = applications.find((item) => item.id === interview.applicationId)
    const company = byId.get(app?.companyId ?? '')
    const date = format(new Date(interview.scheduledAt), 'yyyy-MM-dd')
    const time = format(new Date(interview.scheduledAt), 'HH:mm')
    events.push({
      id: `auto-interview-${interview.id}`,
      title: `${company?.name ?? '未知公司'} ${interview.round}`,
      date,
      time,
      type: '面试',
      color: 'rose',
      linkedTo: { kind: 'interview', id: interview.id },
      isAutoGenerated: true,
    })
  })

  const uniq = new Map<string, CalendarEvent>()
  events.forEach((item) => uniq.set(keyOf(item.linkedTo, item.type, item.date), item))
  return [...uniq.values()]
}
